
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dbsys.AppData
{

using System;
    using System.Collections.Generic;
    
public partial class ClientDashboarD
{

    public int CNo { get; set; }

    public string CName { get; set; }

    public string PName { get; set; }

    public string PetType { get; set; }

    public string PDOB { get; set; }

    public string ADate { get; set; }

    public string ATime { get; set; }

    public string CComment { get; set; }

}

}
