
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dbsys.AppData
{

using System;
    using System.Collections.Generic;
    
public partial class appointment_table
{

    public int ANo { get; set; }

    public string ACName { get; set; }

    public string APName { get; set; }

    public string APetType { get; set; }

    public System.DateTime APDOB { get; set; }

    public System.DateTime AADate { get; set; }

    public string AATime { get; set; }

    public string ACComment { get; set; }

}

}
