
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dbsys.AppData
{

using System;
    using System.Collections.Generic;
    
public partial class View_appointment_recs
{

    public int CNo { get; set; }

    public string ARemarks { get; set; }

    public string AATime { get; set; }

    public string AADate { get; set; }

    public string CName { get; set; }

}

}
